server:
  port: 8080
  servlet:
    context-path: /pltrade
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.233.129:3306/lyu-trade?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  mail:
    host: smtp.qq.com
    username: 401598613@qq.com
    password: engyybbjkjescaaf
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    host: 192.168.233.129
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 0
    connect-timeout: 30000


wx:
  access:
    token:
      corpid: wwd32d99c2c8228e1f
      corpsecret: O11RyWwnXJ3gLX4kp9Nn9wekwfuDM3hN_VwRYIzilF8
  message:
    agentid: 1000002
    msgtype: text


